name: glaregroup
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  jiffy: ^6.4.3
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.13.1
  geolocator: ^13.0.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  flutter_otp_text_field: ^1.1.3
  lottie: ^3.1.3
  flutter_ringtone_player: ^4.0.0+4
  curved_navigation_bar: ^1.0.6
  rating_dialog: ^2.0.4
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa/Nexa-Trial-Heavy.ttf
        - asset: assets/fonts/Nexa/Nexa-Trial-Black.ttf
          weight: 700
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria/Alexandria-VariableFont_wght.ttf
